version: "3"

volumes:
  db:

services:
  tracker:
    image: zoton2/donation-tracker:latest
    volumes:
      - db:/var/www/db
    restart: always
    ports:
      - 127.0.0.1:8000:8000/tcp
    environment:
      - TRACKER_DOMAIN=example.com
      - TRACKER_SECRET_KEY=SomeKeyGoesHere
      - TRACKER_TIME_ZONE=Europe/Stockholm
  repeater:
    image: zoton2/donation-tracker:repeater-latest
    restart: always
    ports:
      - 127.0.0.1:8080:8080/tcp
    environment:
      - REPEATER_SECRET_KEY=SomeKeyGoesHere