version: "3"

volumes:
  db:

services:
  app:
    image: zoton2/donation-tracker:latest
    volumes:
      - db:/var/www/db
    restart: always
    ports:
      - 8000:8000/tcp
    environment:
      - TRACKER_DOMAIN=example.com
      - TRACKER_SECRET_KEY=SomeKeyGoesHere